language: php

php:
  - 7.1
  - 7.2
node_js:
  - 6
  - 7
  - 8

sudo: required

cache:
    directories:
        - $HOME/.composer/cache/files
# node_modules are not cached, because we don't shrinkwrap the deps.
#        - node_modules

env:
env:
  matrix: SYMFONY_VERSION=^4.0
  global:
    - SYMFONY_DEPRECATIONS_HELPER="/.*each.*/"
    - SYMFONY_PHPUNIT_DIR=.phpunit SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
    - KERNEL_CLASS=Symfony\Cmf\Bundle\RoutingBundle\Tests\Fixtures\App\Kernel
    - SYMFONY_PHPUNIT_VERSION=5.7
    - TEST_INSTALLATION=false
    - LANG=php
    - NODE_RELEASE=6.x
    - STABILITY=dev

matrix:
  include:
    - php: 7.1
      dist: trusty
      node_js: 6
      env: LANG=js
    - php: 7.1
      node_js: 7
      env: LANG=js
    - php: 7.1
      node_js: 8
      env: LANG=js
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_VERSION=2.8.* SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.2
      env: SYMFONY_VERSION=3.3.*
    - env: TEST_INSTALLATION=true
  fast_finish: true
  allow_failures:
    - env: TEST_INSTALLATION=true

before_install:
  - if [ "$LANG" = "js" ]; then npm run travis:install; fi
  - if [ "$LANG" = "php" ]; then phpenv config-rm xdebug.ini || true; fi
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; composer config prefer-stable true; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)

install: travis_wait composer update --prefer-dist $COMPOSER_FLAGS

script:
  - if [ "$LANG" = "js" ]; then npm test; fi
  - if [ "$LANG" = "php" ]; then make test; fi

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
